name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: GolangCI-Lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          go_version_file: "go.mod"
          golangci_lint_version: "v2.4.0"
          level: "info"
          fail_level: "error"
          reporter: "github-pr-review"
          golangci_lint_flags: --config=./.golangci.yml